import type { Metadata } from 'next'
import { Inter} from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/context/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Grades app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/x-icon" href="@/favicon.ico"></link>
      </head>
      <body className={inter.className}><AuthProvider>{children}</AuthProvider></body>
    </html>
  )
}
